### ISSUE TITLE
Reduce the scope of notebook 1 and 2

### ISSUE THREAD

**Issue by GregoryAshton** [GregoryAshton/PH3010_advanced_python#6]

**Comment by ramackie** [comment]
* [x] Consider removing challenge 1.4 (recursion), or putting it under bonus/extra content
* [x] Make a pull request for the typo under classes (I'll attempt this)
* [x] Change the y dot into a z dot in the last expression in this screenshot 
![Screenshot 2022-07-28 145029](https://user-images.githubusercontent.com/109959748/181521969-3c904f24-a4f6-426b-889c-c29cf58b8238.png)


- Most of notebook 1 is a useful for the group project, especially challenges 1.7-1.9
- I'm unsure about notebook 2. I think if there are going to be cuts, most of it should come from here; I didn't finish all of notebook 2 so maybe some of the challenges will be quite useful in completing the project, but again, I didn't get far in the project.  
- Given how I approached the project, notebook 1 was more useful
